# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7703f30dfef3651dc1d320cecfce48c7ab1cb226a8778cea9b8318b9e97d9adebb78944ec56d245a0625032bfbf5e2271faac48b69047dac4d67ada7146b84d5

test:
  secret_key_base: 5aef9aca0b02e78edaff7f87478b12c44c5dfe33ab87eb2e4334e3e0d94b64e6e7450c37f405e71ce3472fcba432c6d47ec780378353d66d2fa9de81c4e7d5cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:

  secret_key_base: <%= ENV["LALULI_SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["LALULI_SECRET_KEY_BASE"] %>